### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by prisae** [emsig/sdirectives#1]
- [ ] Store `m0`, `mref`, and `obs` (?)
- [ ] Add hook for plot per iteration
- [ ] Load/get
- [ ] Restarting possibility from directive alone
